name: gc_wizard
description: GC Wizard
version: 1.4.1+86

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  base32: ^1.1.2
  diacritic: ^0.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.10.1+1
  flutter_map_marker_popup: ^0.1.4
  flutter_map_tappable_polyline: ^1.2.0
  fluttertoast: ^7.1.1
  intl: ^0.16.1
  location: ^3.0.2
  mask_text_input_formatter: ^1.1.0
  math_expressions: ^2.0.2
#  open_file: ^3.0.3
  package_info: ^0.4.3
  path: ^1.7.0
  path_provider: ^1.6.18
  permission_handler: ^5.0.1+1
  pointycastle: ^1.0.2
  prefs: ^3.2.1
  provider: ^4.3.2+2
  qr_flutter: ^3.2.0
  share_extend: ^1.1.9
  touchable: ^0.2.0
  uuid: ^2.2.2
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/logo/
    - assets/coordinates/
    - assets/quadgrams/
    - assets/tokens/
    - assets/symbol_tables/
    - assets/symbol_tables/adlam/
    - assets/symbol_tables/alchemy/
    - assets/symbol_tables/alchemy_alphabet/
    - assets/symbol_tables/alphabetum_arabum/
    - assets/symbol_tables/alphabetum_egiptiorum/
    - assets/symbol_tables/alphabetum_gothicum/
    - assets/symbol_tables/angerthas_cirth/
    - assets/symbol_tables/antiker/
    - assets/symbol_tables/arabic_indian_numerals/
    - assets/symbol_tables/arcadian/
    - assets/symbol_tables/ath/
    - assets/symbol_tables/atlantean/
    - assets/symbol_tables/aurebesh/
    - assets/symbol_tables/australian_sign_language/
    - assets/symbol_tables/babylonian_numerals/
    - assets/symbol_tables/ballet/
    - assets/symbol_tables/barbier/
    - assets/symbol_tables/barcode39/
    - assets/symbol_tables/baudot/
    - assets/symbol_tables/birds_on_a_wire/
    - assets/symbol_tables/blox/
    - assets/symbol_tables/brahmi_numerals/
    - assets/symbol_tables/braille/
    - assets/symbol_tables/british_sign_language/
    - assets/symbol_tables/chappe_v1/
    - assets/symbol_tables/chappe_v2/
    - assets/symbol_tables/chappe_v3/
    - assets/symbol_tables/cherokee/
    - assets/symbol_tables/chinese_numerals/
    - assets/symbol_tables/cistercian/
    - assets/symbol_tables/color_code/
    - assets/symbol_tables/color_honey/
    - assets/symbol_tables/color_tokki/
    - assets/symbol_tables/cyrillic/
    - assets/symbol_tables/cyrillic_numbers/
    - assets/symbol_tables/daedric/
    - assets/symbol_tables/dagger/
    - assets/symbol_tables/dancing_men/
    - assets/symbol_tables/deafblind/
    - assets/symbol_tables/devanagari_numerals/
    - assets/symbol_tables/dni/
    - assets/symbol_tables/dni_colors/
    - assets/symbol_tables/dni_numbers/
    - assets/symbol_tables/doremi/
    - assets/symbol_tables/dragon_language/
    - assets/symbol_tables/dragon_runes/
    - assets/symbol_tables/eastern_arabic_indian_numerals/
    - assets/symbol_tables/egyptian_numerals/
    - assets/symbol_tables/elia/
    - assets/symbol_tables/enochian/
    - assets/symbol_tables/eurythmy/
    - assets/symbol_tables/fakoo/
    - assets/symbol_tables/finger/
    - assets/symbol_tables/finger_numbers/
    - assets/symbol_tables/flags/
    - assets/symbol_tables/flags_german_kriegsmarine/
    - assets/symbol_tables/flags_nato/
    - assets/symbol_tables/fonic/
    - assets/symbol_tables/four_triangles/
    - assets/symbol_tables/freemason/
    - assets/symbol_tables/freemason_v2/
    - assets/symbol_tables/futurama/
    - assets/symbol_tables/futurama_2/
    - assets/symbol_tables/gallifreyan/
    - assets/symbol_tables/gargish/
    - assets/symbol_tables/genreich/
    - assets/symbol_tables/glagolitic/
    - assets/symbol_tables/gnommish/
    - assets/symbol_tables/greek_numerals/
    - assets/symbol_tables/hazard/
    - assets/symbol_tables/hebrew/
    - assets/symbol_tables/hebrew_v2/
    - assets/symbol_tables/hexahue/
    - assets/symbol_tables/hieratic_numerals/
    - assets/symbol_tables/hobbit_runes/
    - assets/symbol_tables/hvd/
    - assets/symbol_tables/hylian_skyward_sword/
    - assets/symbol_tables/hylian_twilight_princess_gcn/
    - assets/symbol_tables/hylian_twilight_princess_wii/
    - assets/symbol_tables/hylian_wind_waker/
    - assets/symbol_tables/hymmnos/
    - assets/symbol_tables/iching/
    - assets/symbol_tables/illuminati_v1/
    - assets/symbol_tables/illuminati_v2/
    - assets/symbol_tables/intergalactic/
    - assets/symbol_tables/iokharic/
    - assets/symbol_tables/japanese_numerals/
    - assets/symbol_tables/kabouter_abc/
    - assets/symbol_tables/kabouter_abc_1947/
    - assets/symbol_tables/kartrak/
    - assets/symbol_tables/kharoshthi/
    - assets/symbol_tables/klingon/
    - assets/symbol_tables/klingon_klinzhai/
    - assets/symbol_tables/krempel/
    - assets/symbol_tables/krypton/
    - assets/symbol_tables/lorm/
    - assets/symbol_tables/magicode/
    - assets/symbol_tables/marain/
    - assets/symbol_tables/marain_v2/
    - assets/symbol_tables/matoran/
    - assets/symbol_tables/maya_numerals/
    - assets/symbol_tables/maze/
    - assets/symbol_tables/minimoys/
    - assets/symbol_tables/moon/
    - assets/symbol_tables/murray/
    - assets/symbol_tables/murraybaudot/
    - assets/symbol_tables/musica/
    - assets/symbol_tables/new_zealand_sign_language/
    - assets/symbol_tables/notes_doremi/
    - assets/symbol_tables/notes_notevalues/
    - assets/symbol_tables/notes_names_altoclef/
    - assets/symbol_tables/notes_names_bassclef/
    - assets/symbol_tables/notes_names_trebleclef/
    - assets/symbol_tables/notes_restvalues/
    - assets/symbol_tables/ogham/
    - assets/symbol_tables/optical_fiber_fotag/
    - assets/symbol_tables/optical_fiber_iec60304/
    - assets/symbol_tables/optical_fiber_swisscom/
    - assets/symbol_tables/phoenician/
    - assets/symbol_tables/pipeline/
    - assets/symbol_tables/pixel/
    - assets/symbol_tables/planet/
    - assets/symbol_tables/pokemon_unown/
    - assets/symbol_tables/postnet/
    - assets/symbol_tables/puzzle/
    - assets/symbol_tables/quadoo/
    - assets/symbol_tables/reality/
    - assets/symbol_tables/red_herring/
    - assets/symbol_tables/resistor/
    - assets/symbol_tables/rhesus_a/
    - assets/symbol_tables/rm4scc/
    - assets/symbol_tables/romulan/
    - assets/symbol_tables/runes/
    - assets/symbol_tables/sanluca/
    - assets/symbol_tables/sarati/
    - assets/symbol_tables/semaphore/
    - assets/symbol_tables/sign/
    - assets/symbol_tables/skullz/
    - assets/symbol_tables/slash_and_pipe/
    - assets/symbol_tables/solmisation/
    - assets/symbol_tables/space_invaders/
    - assets/symbol_tables/spintype/
    - assets/symbol_tables/stippelcode/
    - assets/symbol_tables/suetterlin/
    - assets/symbol_tables/sunuz/
    - assets/symbol_tables/tamil_numerals/
    - assets/symbol_tables/templers/
    - assets/symbol_tables/tenctonese/
    - assets/symbol_tables/tengwar_beleriand/
    - assets/symbol_tables/tengwar_classic/
    - assets/symbol_tables/tengwar_general/
    - assets/symbol_tables/terzi/
    - assets/symbol_tables/theban/
    - assets/symbol_tables/three_squares/
    - assets/symbol_tables/tines/
    - assets/symbol_tables/tomtom/
    - assets/symbol_tables/trafficsigns_germany/
    - assets/symbol_tables/ulog/
    - assets/symbol_tables/utopian/
    - assets/symbol_tables/visitor_1984/
    - assets/symbol_tables/visitor_2009/
    - assets/symbol_tables/vulcanian/
    - assets/symbol_tables/wakandan/
    - assets/symbol_tables/webdings/
    - assets/symbol_tables/windforce_beaufort/
    - assets/symbol_tables/windforce_knots/
    - assets/symbol_tables/window/
    - assets/symbol_tables/wingdings/
    - assets/symbol_tables/wingdings2/
    - assets/symbol_tables/wingdings3/
    - assets/symbol_tables/yan_koryani/
    - assets/symbol_tables/yinyang/
    - assets/symbol_tables/zentradi/
    - assets/symbol_tables/zodiac_z340/
    - assets/symbol_tables/zodiac_z408/

flutter_icons:
  image_path: "assets/logo/circle_border_1024_gold.png"
  android: true
  ios: true